package com.navinfo.omqs.db

class Code2NameMap {
    val electronEyeKindMap = mapOf(
        1 to "超高",
        2 to "超低",
        3 to "移动",
        4 to "可变",
        5 to "分车道",
        6 to "分车种",
        7 to "车灯",
        8 to "占车道",
        9 to "过路口",
        10 to "闯红灯",
        11 to "路况",
        12 to "单行",
        13 to "非机动",
        14 to "出入口",
        15 to "公交",
        16 to "禁转",
        17 to "掉头",
        18 to "应急",
        19 to "标线",
        20 to "区间S",
        21 to "区间E",
        22 to "停车",
        23 to "尾号",
        24 to "环保",
        25 to "安全带",
        26 to "手机",
        27 to "行人",
        28 to "禁令",
        29 to "鸣笛",
        30 to "年检",
        31 to "尾气",
        32 to "交通灯",
        33 to "专用",
        34 to "标线",
        35 to "违章",
        36 to "卡车",
        37 to "限时长",
    )
}